apiVersion: apps/v1
kind: Deployment
metadata:
  name: fah-gpu-cpu
  labels:
    app: fah-gpu-cpu  
spec:
  selector:
    matchLabels:
      app: fah-gpu-cpu
  replicas: 30 # Set number of replicas to run - one replica per node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: fah-gpu-cpu
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fah-gpu-cpu
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: fah-gpu-cpu
        image: "ivukotic/folding-at-home:latest"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m # How much CPU you wish to donate per node
            memory: 2Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: 100m
            memory: 256Mi
            nvidia.com/gpu: "1"
      priorityClassName: low-priority