apiVersion: apps/v1
kind: Deployment
metadata:
  name: fah-gpu
  labels:
    app: fah-gpu  
spec:
  selector:
    matchLabels:
      app: fah-gpu
  replicas: 2 # Set number of replicas to run - one replica per node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: fah-gpu
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fah-gpu
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: fah-gpu
        image: "ivukotic/folding-at-home:latest"
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: "1" # how many GPU'S should each pod have
          requests:
            nvidia.com/gpu: "1"
      priorityClassName: low-priority